"""user_add_column_age

Revision ID: a0f3ae2a0a0c
Revises: 3ab683685864
Create Date: 2022-11-03 10:29:14.686944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f3ae2a0a0c'
down_revision = '3ab683685864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.execute("UPDATE public.user SET age = 18")
    op.alter_column('user','age',nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
